export const cities = [
  { id: 1, city_name: "Lahore", label: "Lahore (لاہور)", short_code: "LHE" },

  {
    id: 2,
    city_name: "Rawalpindi / Islamabad",
    label: "Rawalpindi / Islamabad (اسلام آباد)",
    short_code: "RWP",
  },
  {
    id: 3,
    city_name: "Batkhela",
    label: "Batkhela (بٹ خیلہ)",
    short_code: "BATK",
  },
  { id: 4, city_name: "Bhakkar", label: "Bhakkar (بھکر)", short_code: "BHK" },
  { id: 5, city_name: "Gujrat", label: "Gujrat (گجرات)", short_code: "GJT" },
  {
    id: 6,
    city_name: "Hyderabad",
    label: "Hyderabad (حیدرآباد)",
    short_code: "HYD",
  },
  {
    id: 7,
    city_name: "Mianwali",
    label: "Mianwali (میانوالی)",
    short_code: "MNW",
  },
  { id: 8, city_name: "Moro", label: "Moro (مورو)", short_code: "MOR" },
  { id: 9, city_name: "Murree", label: "Murree (مری)", short_code: "MUR" },
  {
    id: 10,
    city_name: "Bhalwal",
    label: "Bhalwal (بهلوال)",
    short_code: "BHL",
  },
  {
    id: 11,
    city_name: "Rahim Yar Khan",
    label: "Rahim Yar Khan (رحیم یار خان)",
    short_code: "RYK",
  },
  { id: 12, city_name: "Swat", label: "Swat (سوات)", short_code: "SWT" },
  { id: 13, city_name: "Chakwal", label: "Chakwal (چکوال)", short_code: "CHK" },
  { id: 14, city_name: "Sakrand", label: "Sakrand (سکرنڈ)", short_code: "SKR" },
  {
    id: 15,
    city_name: "Haripur",
    label: "Haripur (ہری پور)",
    short_code: "HRP",
  },
  {
    id: 16,
    city_name: "Faisalabad",
    label: "Faisalabad (فیصل آباد)",
    short_code: "FSB",
  },
  {
    id: 17,
    city_name: "Chichawatni",
    label: "Chichawatni (چیچہ وطنی)",
    short_code: "CHCW",
  },
  {
    id: 18,
    city_name: "Muzafargarh",
    label: "Muzafargarh (مظفر گڑھ)",
    short_code: "MUZF",
  },
  {
    id: 19,
    city_name: "Mian Chanu",
    label: "Mian Chanu (مِياں چنُّوں)",
    short_code: "MCHN",
  },
  { id: 20, city_name: "Multan", label: "Multan (ملتان)", short_code: "MUL" },
  {
    id: 21,
    city_name: "Sargodha",
    label: "Sargodha (سرگودھا)",
    short_code: "SGH",
  },
  {
    id: 22,
    city_name: "Nowshera",
    label: "Nowshera (نوشہرہ)",
    short_code: "NOW",
  },
  { id: 23, city_name: "Jhang", label: "Jhang (جھنگ)", short_code: "JHA" },
  { id: 24, city_name: "Jhelum", label: "Jhelum (جہلم)", short_code: "JHEL" },
  {
    id: 25,
    city_name: "Lodhran",
    label: "Lodhran (لودھراں)",
    short_code: "LDH",
  },
  {
    id: 26,
    city_name: "Abbottabad",
    label: "Abbottabad (ایبٹ آباد)",
    short_code: "ABT",
  },
  {
    id: 27,
    city_name: "Jahanian",
    label: "Jahanian (جہانیاں)",
    short_code: "JHNN",
  },
  {
    id: 28,
    city_name: "Zahirpir",
    label: "Zahirpir (ظاہرپیر)",
    short_code: "ZHI",
  },
  { id: 29, city_name: "Karachi", label: "Karachi (کراچی)", short_code: "KHI" },
  {
    id: 30,
    city_name: "Ahmed Pur",
    label: "Ahmed Pur (احمد پور)",
    short_code: "APE",
  },
  {
    id: 31,
    city_name: "Bahawalpur",
    label: "Bahawalpur (بہاولپور)",
    short_code: "BAH",
  },
  { id: 32, city_name: "Daska", label: "Daska (ڈسکہ)", short_code: "DSK" },
  {
    id: 33,
    city_name: "Dera Ghazi Khan",
    label: "Dera Ghazi Khan (ڈیرہ غازی خان)",
    short_code: "DGK",
  },
  {
    id: 34,
    city_name: "Dera Ismail Khan",
    label: "Dera Ismail Khan (ڈیرہ اسماعیل خان)",
    short_code: "DIK",
  },
  { id: 35, city_name: "Dharki", label: "Dharki (ڈھرکی)", short_code: "DHR" },
  {
    id: 36,
    city_name: "Khan Pur",
    label: "Khan Pur (خان پور)",
    short_code: "KPR",
  },
  {
    id: 37,
    city_name: "Khanewal",
    label: "Khanewal (خانیوال)",
    short_code: "KHW",
  },
  { id: 38, city_name: "Kohat", label: "Kohat (کوہاٹ)", short_code: "KHT" },
  {
    id: 39,
    city_name: "Okara City",
    label: "Okara City (اوکاڑہ سٹی)",
    short_code: "OKR",
  },
  {
    id: 40,
    city_name: "Peshawar",
    label: "Peshawar (پشاور)",
    short_code: "PEW",
  },
  { id: 41, city_name: "Mardan", label: "Mardan (مردان)", short_code: "MRD" },
  {
    id: 42,
    city_name: "Sadiqabad",
    label: "Sadiqabad (صادق آباد)",
    short_code: "SAQ",
  },
  {
    id: 43,
    city_name: "Sahiwal",
    label: "Sahiwal (ساہیوال)",
    short_code: "SAW",
  },
  {
    id: 44,
    city_name: "Sialkot",
    label: "Sialkot (سیالکوٹ)",
    short_code: "SIAL",
  },
  { id: 45, city_name: "Sukkur", label: "Sukkur (سکھر)", short_code: "SUK" },
  {
    id: 46,
    city_name: "Lakki Marwat",
    label: "Lakki Marwat (لکی مروت)",
    short_code: "LMR",
  },
  {
    id: 47,
    city_name: "Gujranwala",
    label: "Gujranwala (گوجرانوالہ)",
    short_code: "GJW",
  },
  {
    id: 48,
    city_name: "Balkasar",
    label: "Balkasar (بلکاسر)",
    short_code: "BLK",
  },
  {
    id: 49,
    city_name: "Naushahro Feroze",
    label: "Naushahro Feroze (نوشہرو فیروز)",
    short_code: "NSF",
  },
  {
    id: 50,
    city_name: "Larkana",
    label: "Larkana (لاڑکانہ)",
    short_code: "LRK",
  },
  {
    id: 51,
    city_name: "Danda Sha Bilawal",
    label: "Danda Sha Bilawal (ڈنڈا شاہ بلاول)",
    short_code: "DSB",
  },
  { id: 52, city_name: "Ghotki", label: "Ghotki (گھوٹکی)", short_code: "GTK" },
  {
    id: 53,
    city_name: "Naudero",
    label: "Naudero (نوڈیرو)",
    short_code: "NDR",
  },
  { id: 54, city_name: "Tarhada", label: "Tarhada (ترہڈا)", short_code: "TRD" },
  {
    id: 55,
    city_name: "Talagang",
    label: "Talagang (تلہ گنگ)",
    short_code: "TLG",
  },
  {
    id: 56,
    city_name: "Samundri",
    label: "Samundri (سمندری)",
    short_code: "SDR",
  },
  { id: 57, city_name: "Rikhi", label: "Rikhi (رِکھی)", short_code: "RKI" },
  {
    id: 58,
    city_name: "Pano Aqil",
    label: "Pano Aqil (پنو عاقل)",
    short_code: "PNQ",
  },
  { id: 59, city_name: "Madeji", label: "Madeji (میڈی جی)", short_code: "MDJ" },
  {
    id: 60,
    city_name: "Abdul Hakim",
    label: "Abdul Hakim (عبد الحکیم)",
    short_code: "ADH",
  },
  {
    id: 61,
    city_name: "Rajanpur",
    label: "Rajanpur (راجن پُور)",
    short_code: "RJP",
  },
  {
    id: 62,
    city_name: "Kot Addu",
    label: "Kot Addu (كوٹ ادُّو‎)",
    short_code: "KTU",
  },
  {
    id: 63,
    city_name: "Taunsa Sharif",
    label: "Taunsa Sharif (تونسه شريف)",
    short_code: "TUA",
  },
  { id: 64, city_name: "Jatoi", label: "Jatoi (جتوئ)", short_code: "JOT" },
  { id: 65, city_name: "Alipur", label: "Alipur (علي پور)", short_code: "AIP" },
  { id: 67, city_name: "Quetta", label: "Quetta (کوئٹہ‎)", short_code: "QTA" },
  {
    id: 68,
    city_name: "Sanawan",
    label: "Sanawan (سناواں)",
    short_code: "SNN",
  },
  { id: 69, city_name: "Layyah", label: "Layyah (لیہ)", short_code: "LYH" },
  {
    id: 70,
    city_name: "Shahkot",
    label: "Shahkot (شاہكوٹ)",
    short_code: "SHT",
  },
  {
    id: 71,
    city_name: "Mansehra",
    label: "Mansehra (مانسہرہ)",
    short_code: "MHA",
  },
  {
    id: 72,
    city_name: "Chowk Qureshi",
    label: "Chowk Qureshi (چوک قریشی)",
    short_code: "CHQ",
  },
  {
    id: 73,
    city_name: "Haroonabad",
    label: "Haroonabad (ہارون آباد)",
    short_code: "HAR",
  },
  { id: 74, city_name: "Gawadar", label: "Gawadar (گوادر)", short_code: "GWD" },
  {
    id: 75,
    city_name: "Muzzafarabad",
    label: "Muzzafarabad (مُظَفَّر آباد)",
    short_code: "MZB",
  },
  {
    id: 76,
    city_name: "Gabd, Rimdan Border",
    label: "Gabd, Rimdan Border (رمدان بارڈر)",
    short_code: "GBD",
  },
  { id: 77, city_name: "Ormara", label: "Ormara (اورماڑا)", short_code: "ORW" },
  { id: 78, city_name: "Turbat", label: "Turbat (تربت)", short_code: "TUR" },
  {
    id: 79,
    city_name: "Shikarpur",
    label: "Shikarpur (شکارپور)",
    short_code: "SKP",
  },
  {
    id: 80,
    city_name: "Panjgur",
    label: "Panjgur (پنجگور)",
    short_code: "PJG",
  },
  { id: 81, city_name: "Pasni", label: "Pasni (پسنى)", short_code: "PSI" },
  { id: 82, city_name: "Jiwani", label: "Jiwani (جيونى)", short_code: "JIW" },
  { id: 83, city_name: "Rohri", label: "Rohri (روہڑی)", short_code: "RCW" },
  {
    id: 84,
    city_name: "Fort Abbas",
    label: "Fort Abbas (فورٹ عباس)",
    short_code: "FAB",
  },
  { id: 86, city_name: "Bannu", label: "Bannu", short_code: "BNP" },
  { id: 87, city_name: "Wahova", label: "Wahova", short_code: "WHOA" },
  { id: 88, city_name: "Sawat", label: "Sawat", short_code: "SAT" },
  { id: 89, city_name: "Kharian", label: "Kharian", short_code: "KHA" },
  { id: 90, city_name: "Hasilpur", label: "Hasilpur", short_code: "HSP" },
  { id: 91, city_name: "Wazirabad", label: "Wazirabad", short_code: "WZA" },
  { id: 92, city_name: "Lala Moosa", label: "Lala Moosa", short_code: "LLM" },
  { id: 93, city_name: "Battagram", label: "Battagram", short_code: "BTG" },
  { id: 94, city_name: "Thakot", label: "Thakot", short_code: "TKT" },
  { id: 95, city_name: "Kamalia", label: "Kamalia", short_code: "KML" },
  { id: 96, city_name: "Vehari", label: "Vehari", short_code: "VHR" },
  { id: 97, city_name: "Burewala", label: "Burewala", short_code: "BRW" },
  { id: 99, city_name: "Dunyapur", label: "Dunyapur", short_code: "DNY" },
  { id: 101, city_name: "Jampur", label: "Jampur", short_code: "JAM" },
  {
    id: 202,
    city_name: "Zafar Chowk",
    label: "Zafar Chowk",
    short_code: "ZFC",
  },
  {
    id: 203,
    city_name: "Mamukanjan",
    label: "Mamukanjan  (ماموں کانجن)",
    short_code: "Mamu",
  },
];

const citiesWithTerminal = [
  {
    id: 57,
    name: "Rikhi (رِکھی)",
    short_code: "RKI",
    terminals: [
      {
        id: 160,
        name: "Rikhi",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "RKI",
        city_code: "RKI",
        city: "Rikhi (رِکھی)",
      },
    ],
  },
  {
    id: 58,
    name: "Pano Aqil (پنو عاقل)",
    short_code: "PNQ",
    terminals: [
      {
        id: 161,
        name: "Pano Aqil",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "PNQ",
        city_code: "PNQ",
        city: "Pano Aqil (پنو عاقل)",
      },
    ],
  },
  {
    id: 59,
    name: "Madeji (میڈی جی)",
    short_code: "MDJ",
    terminals: [
      {
        id: 162,
        name: "Madeji",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "MDJ",
        city_code: "MDJ",
        city: "Madeji (میڈی جی)",
      },
    ],
  },
  {
    id: 72,
    name: "Chowk Qureshi (چوک قریشی)",
    short_code: "CHQ",
    terminals: [
      {
        id: 182,
        name: "Chowk Qureshi",
        latitude: null,
        longitude: null,
        address: "Chowk Qureshi, Khanewal, Punjab",
        short_code: "CHQ",
        city_code: "CHQ",
        city: "Chowk Qureshi (چوک قریشی)",
      },
    ],
  },
  {
    id: 60,
    name: "Abdul Hakim (عبد الحکیم)",
    short_code: "ADH",
    terminals: [
      {
        id: 166,
        name: "Abdul Hakim",
        latitude: null,
        longitude: null,
        address: "Abdul Hakim, Khanewal, Punjab",
        short_code: "ADH",
        city_code: "ADH",
        city: "Abdul Hakim (عبد الحکیم)",
      },
    ],
  },
  {
    id: 61,
    name: "Rajanpur (راجن پُور)",
    short_code: "RJP",
    terminals: [
      {
        id: 167,
        name: "Rajanpur",
        latitude: null,
        longitude: null,
        address: "Rajanpur",
        short_code: "RJP",
        city_code: "RJP",
        city: "Rajanpur (راجن پُور)",
      },
    ],
  },
  {
    id: 62,
    name: "Kot Addu (كوٹ ادُّو‎)",
    short_code: "KTU",
    terminals: [
      {
        id: 169,
        name: "Kot Addu",
        latitude: null,
        longitude: null,
        address: "Ward Number 14E Kot Addu, Muzaffargarh",
        short_code: "KTU",
        city_code: "KTU",
        city: "Kot Addu (كوٹ ادُّو‎)",
      },
    ],
  },
  {
    id: 63,
    name: "Taunsa Sharif (تونسه شريف)",
    short_code: "TUA",
    terminals: [
      {
        id: 170,
        name: "Taunsa Sharif",
        latitude: null,
        longitude: null,
        address: "Taunsa Sharif",
        short_code: "TUA",
        city_code: "TUA",
        city: "Taunsa Sharif (تونسه شريف)",
      },
      {
        id: 236,
        name: "Mangrotha Chowrangi Taunsa",
        latitude: null,
        longitude: null,
        address: "Taunsa Shareef Mangrotha Chowrangi",
        short_code: "TUA-GBS",
        city_code: "TUA",
        city: "Taunsa Sharif (تونسه شريف)",
      },
    ],
  },
  {
    id: 64,
    name: "Jatoi (جتوئ)",
    short_code: "JOT",
    terminals: [
      {
        id: 188,
        name: "Saddar Jatoi",
        latitude: null,
        longitude: null,
        address: "Main Saddar markaz, Jatoi",
        short_code: "JOT-SAD",
        city_code: "JOT",
        city: "Jatoi (جتوئ)",
      },
      {
        id: 171,
        name: "Jatoi",
        latitude: null,
        longitude: null,
        address:
          "Indus Hotel & Restaurant Near Commissioner House Alipur,Waseb Hotel",
        short_code: "JOT",
        city_code: "JOT",
        city: "Jatoi (جتوئ)",
      },
    ],
  },
  {
    id: 65,
    name: "Alipur (علي پور)",
    short_code: "AIP",
    terminals: [
      {
        id: 172,
        name: "Alipur",
        latitude: null,
        longitude: null,
        address: "Alipur, Muzaffargarh, Punjab",
        short_code: "AIP",
        city_code: "AIP",
        city: "Alipur (علي پور)",
      },
    ],
  },
  {
    id: 67,
    name: "Quetta (کوئٹہ‎)",
    short_code: "QTA",
    terminals: [
      {
        id: 175,
        name: "Quetta Faisal Mover Terminal",
        latitude: null,
        longitude: null,
        address: "Quetta, Balochistan.",
        short_code: "QTA-FM",
        city_code: "QTA",
        city: "Quetta (کوئٹہ‎)",
      },
      {
        id: 207,
        name: "Sadabahar Terminal Quetta",
        latitude: 30.177835933485085,
        longitude: 66.99378552883536,
        address: "Sadabahar Terminal, Sariyab Road",
        short_code: "QTA-SDB",
        city_code: "QTA",
        city: "Quetta (کوئٹہ‎)",
      },
      {
        id: 232,
        name: "Quetta",
        latitude: null,
        longitude: null,
        address: "Jabal e Noor Bus Stop",
        short_code: "QTA-JN",
        city_code: "QTA",
        city: "Quetta (کوئٹہ‎)",
      },
      {
        id: 252,
        name: "Al Imdad Quetta Jable noor adda",
        latitude: null,
        longitude: null,
        address: "Spinny Road, Quetta, Balochistan, Pakistan",
        short_code: "QTA-AI",
        city_code: "QTA",
        city: "Quetta (کوئٹہ‎)",
      },
    ],
  },
  {
    id: 68,
    name: "Sanawan (سناواں)",
    short_code: "SNN",
    terminals: [
      {
        id: 176,
        name: "Sanawan Terminal",
        latitude: null,
        longitude: null,
        address: "Sanawan",
        short_code: "SNN",
        city_code: "SNN",
        city: "Sanawan (سناواں)",
      },
    ],
  },
  {
    id: 69,
    name: "Layyah (لیہ)",
    short_code: "LYH",
    terminals: [
      {
        id: 177,
        name: "Layyah",
        latitude: null,
        longitude: null,
        address: "Faiz Chowk, Near PSO Petrol Pump",
        short_code: "LYH-FM",
        city_code: "LYH",
        city: "Layyah (لیہ)",
      },
      {
        id: 294,
        name: "Mahar basheer movers terminal",
        latitude: null,
        longitude: null,
        address: "Bypass Mahar basheer movers D class",
        short_code: "LYH-BYP",
        city_code: "LYH",
        city: "Layyah (لیہ)",
      },
      {
        id: 223,
        name: "General Bus Stand Layyah",
        latitude: null,
        longitude: null,
        address: "Lari Adda Balcoh Transport",
        short_code: "LYH-GBS",
        city_code: "LYH",
        city: "Layyah (لیہ)",
      },
    ],
  },
  {
    id: 70,
    name: "Shahkot (شاہكوٹ)",
    short_code: "SHT",
    terminals: [
      {
        id: 179,
        name: "Shahkot",
        latitude: null,
        longitude: null,
        address: "Faisalabad Road, Shahkot",
        short_code: "SHT",
        city_code: "SHT",
        city: "Shahkot (شاہكوٹ)",
      },
    ],
  },
  {
    id: 71,
    name: "Mansehra (مانسہرہ)",
    short_code: "MHA",
    terminals: [
      {
        id: 180,
        name: "Mansehra",
        latitude: null,
        longitude: null,
        address: "Mansehra, Khyber Pakhtunkhwa",
        short_code: "MHA",
        city_code: "MHA",
        city: "Mansehra (مانسہرہ)",
      },
      {
        id: 225,
        name: "General Bus Stand Mansehra",
        latitude: null,
        longitude: null,
        address: "Mansehra Lari Adda Near Dubai Hotel",
        short_code: "MHA-GBS",
        city_code: "MHA",
        city: "Mansehra (مانسہرہ)",
      },
      {
        id: 249,
        name: "Hazara Mover Terminal Mansehra",
        latitude: null,
        longitude: null,
        address: "Hazara Mover Terminal Lari Adda Road Mansehra",
        short_code: "MHA-HM",
        city_code: "MHA",
        city: "Mansehra (مانسہرہ)",
      },
    ],
  },
  {
    id: 73,
    name: "Haroonabad (ہارون آباد)",
    short_code: "HAR",
    terminals: [
      {
        id: 187,
        name: "Rohri Haroonabad",
        latitude: null,
        longitude: null,
        address: "Rohri Main Station, Haroonabad",
        short_code: "HAR-RHR",
        city_code: "HAR",
        city: "Haroonabad (ہارون آباد)",
      },
      {
        id: 192,
        name: "Saddar Haroonabad Bus Stop",
        latitude: null,
        longitude: null,
        address: "Main Haroonabad Bus Stop Saddar",
        short_code: "HAR-SAD",
        city_code: "HAR",
        city: "Haroonabad (ہارون آباد)",
      },
      {
        id: 209,
        name: "Ideal Flying Coach Haroonabad",
        latitude: null,
        longitude: null,
        address: "Ideal Flying Coach Pickup Point",
        short_code: "HAR-IFC",
        city_code: "HAR",
        city: "Haroonabad (ہارون آباد)",
      },
      {
        id: 217,
        name: "Haroonabad",
        latitude: 29.619679169254788,
        longitude: 73.14028031534144,
        address: "Ideal Flying Coach Pickup Point",
        short_code: "HAR-MAKKA",
        city_code: "HAR",
        city: "Haroonabad (ہارون آباد)",
      },
    ],
  },
  {
    id: 74,
    name: "Gawadar (گوادر)",
    short_code: "GWD",
    terminals: [
      {
        id: 190,
        name: "Al Mumtaz Terminal Gawadar",
        latitude: 25.131878259598132,
        longitude: 62.32508437116464,
        address: "Al Mumtaz Coach Service Main Syed Hashmi Road",
        short_code: "GWD-AM",
        city_code: "GWD",
        city: "Gawadar (گوادر)",
      },
    ],
  },
  {
    id: 75,
    name: "Muzzafarabad (مُظَفَّر آباد)",
    short_code: "MZB",
    terminals: [
      {
        id: 198,
        name: "Bela Noor Shah Muzaffarabad",
        latitude: null,
        longitude: null,
        address: "Bus Adda, Bela Noor Shah Road",
        short_code: "MZB-BELA",
        city_code: "MZB",
        city: "Muzzafarabad (مُظَفَّر آباد)",
      },
    ],
  },
  {
    id: 77,
    name: "Ormara (اورماڑا)",
    short_code: "ORW",
    terminals: [
      {
        id: 201,
        name: "Ormara",
        latitude: null,
        longitude: null,
        address: "Al Mumtaz Restaurant Near Zero Point",
        short_code: "ORW-AM",
        city_code: "ORW",
        city: "Ormara (اورماڑا)",
      },
    ],
  },
  {
    id: 78,
    name: "Turbat (تربت)",
    short_code: "TUR",
    terminals: [
      {
        id: 218,
        name: "Al Mumtaz Coach Turbat Stop",
        latitude: 25.975495557841263,
        longitude: 63.057885552771275,
        address: "CPEC Terminal Near Turbat Pasni Road",
        short_code: "TUR-AM",
        city_code: "TUR",
        city: "Turbat (تربت)",
      },
    ],
  },
  {
    id: 79,
    name: "Shikarpur (شکارپور)",
    short_code: "SKP",
    terminals: [
      {
        id: 202,
        name: "Shikarpur",
        latitude: 27.949550290513333,
        longitude: 68.63498382329281,
        address: "Lucky Star Last Stop",
        short_code: "SKP-LKD",
        city_code: "SKP",
        city: "Shikarpur (شکارپور)",
      },
    ],
  },
  {
    id: 76,
    name: "Gabd, Rimdan Border (رمدان بارڈر)",
    short_code: "GBD",
    terminals: [
      {
        id: 195,
        name: "Rimdan Border",
        latitude: 25.381438106940184,
        longitude: 61.676746284189726,
        address: "Main Rimdan Border, Gabd Balochistan",
        short_code: "GBD-RB",
        city_code: "GBD",
        city: "Gabd, Rimdan Border (رمدان بارڈر)",
      },
    ],
  },
  {
    id: 80,
    name: "Panjgur (پنجگور)",
    short_code: "PJG",
    terminals: [
      {
        id: 205,
        name: "Al Mumtaz Panjgur",
        latitude: 27.079910737020008,
        longitude: 64.13372227997655,
        address: "Main Bus Terminal Panjgur",
        short_code: "PJG-AM",
        city_code: "PJG",
        city: "Panjgur (پنجگور)",
      },
    ],
  },
  {
    id: 81,
    name: "Pasni (پسنى)",
    short_code: "PSI",
    terminals: [
      {
        id: 206,
        name: "Al Mumtaz Pasni",
        latitude: 25.328038308993765,
        longitude: 63.42310095582321,
        address: "Main Zero Point Pasni",
        short_code: "PSI-AM",
        city_code: "PSI",
        city: "Pasni (پسنى)",
      },
    ],
  },
  {
    id: 82,
    name: "Jiwani (جيونى)",
    short_code: "JIW",
    terminals: [
      {
        id: 203,
        name: "AL Mumtaz Jiwani",
        latitude: 25.048021116072718,
        longitude: 61.747159571164644,
        address: "Al Mumtaz Coach Service Main Jiwani Road",
        short_code: "JIW-AM",
        city_code: "JIW",
        city: "Jiwani (جيونى)",
      },
    ],
  },
  {
    id: 83,
    name: "Rohri (روہڑی)",
    short_code: "RCW",
    terminals: [
      {
        id: 208,
        name: "Rohri Terminal",
        latitude: null,
        longitude: null,
        address: "Sukkur Bypass Main Terminal Bus Stop",
        short_code: "RCW-SUKK",
        city_code: "RCW",
        city: "Rohri (روہڑی)",
      },
    ],
  },
  {
    id: 84,
    name: "Fort Abbas (فورٹ عباس)",
    short_code: "FAB",
    terminals: [
      {
        id: 211,
        name: "Fort Abbas",
        latitude: 29.19954853346923,
        longitude: 72.85989538662012,
        address: "Kashee Flying Coach Pickup Point",
        short_code: "FAB-KFC",
        city_code: "FAB",
        city: "Fort Abbas (فورٹ عباس)",
      },
    ],
  },
  {
    id: 86,
    name: "Bannu",
    short_code: "BNP",
    terminals: [
      {
        id: 233,
        name: "Bus Adda Bannu",
        latitude: null,
        longitude: null,
        address: "General Bus Stand Bannu",
        short_code: "BNP-GBS",
        city_code: "BNP",
        city: "Bannu",
      },
    ],
  },
  {
    id: 87,
    name: "Wahova",
    short_code: "WHOA",
    terminals: [
      {
        id: 231,
        name: "Wahova",
        latitude: null,
        longitude: null,
        address: "Baloch Transport Adda",
        short_code: "WHOA-BT",
        city_code: "WHOA",
        city: "Wahova",
      },
    ],
  },
  {
    id: 88,
    name: "Sawat",
    short_code: "SAT",
    terminals: [
      {
        id: 238,
        name: "Mingora Sawat",
        latitude: null,
        longitude: null,
        address: "Angro Dehri Chowk Bypass, Mingora, Swat",
        short_code: "SAT-MGA",
        city_code: "SAT",
        city: "Sawat",
      },
    ],
  },
  {
    id: 89,
    name: "Kharian",
    short_code: "KHA",
    terminals: [
      {
        id: 240,
        name: "Kharian",
        latitude: null,
        longitude: null,
        address: "Kharian bus terminal",
        short_code: "KHA-MAIN",
        city_code: "KHA",
        city: "Kharian",
      },
    ],
  },
  {
    id: 90,
    name: "Hasilpur",
    short_code: "HSP",
    terminals: [
      {
        id: 259,
        name: "Muslim Movers stop Hasilpur",
        latitude: null,
        longitude: null,
        address: "Muslim and Rohi Terminal Hasilpur",
        short_code: "HSP-MM",
        city_code: "HSP",
        city: "Hasilpur",
      },
    ],
  },
  {
    id: 91,
    name: "Wazirabad",
    short_code: "WZA",
    terminals: [
      {
        id: 248,
        name: "Main Bypas Wazirabad",
        latitude: null,
        longitude: null,
        address: "Main Bypas Wazirabad",
        short_code: "WZA-NFC",
        city_code: "WZA",
        city: "Wazirabad",
      },
    ],
  },
  {
    id: 92,
    name: "Lala Moosa",
    short_code: "LLM",
    terminals: [
      {
        id: 250,
        name: "Main City Lala Moosa",
        latitude: null,
        longitude: null,
        address: "Main city lala moosa",
        short_code: "LLM-MC",
        city_code: "LLM",
        city: "Lala Moosa",
      },
    ],
  },
  {
    id: 93,
    name: "Battagram",
    short_code: "BTG",
    terminals: [
      {
        id: 262,
        name: "General Bus Stand Battagram",
        latitude: null,
        longitude: null,
        address: "Lari Adda Batgram",
        short_code: "BTG-HM",
        city_code: "BTG",
        city: "Battagram",
      },
    ],
  },
  {
    id: 94,
    name: "Thakot",
    short_code: "TKT",
    terminals: [
      {
        id: 261,
        name: "General Bus Stand Thakot",
        latitude: null,
        longitude: null,
        address: "Lari Adda Thakot.",
        short_code: "TKT-HM",
        city_code: "TKT",
        city: "Thakot",
      },
    ],
  },
  {
    id: 95,
    name: "Kamalia",
    short_code: "KML",
    terminals: [
      {
        id: 255,
        name: "Muslim Movers Stop Kamalia",
        latitude: null,
        longitude: null,
        address: "New Subhan Terminal Kamalia",
        short_code: "KML-MM",
        city_code: "KML",
        city: "Kamalia",
      },
    ],
  },
  {
    id: 96,
    name: "Vehari",
    short_code: "VHR",
    terminals: [
      {
        id: 257,
        name: "Muslim movers Vehari Stop",
        latitude: null,
        longitude: null,
        address: "Nadir Terminal Vehari",
        short_code: "VHR-MM",
        city_code: "VHR",
        city: "Vehari",
      },
    ],
  },
  {
    id: 97,
    name: "Burewala",
    short_code: "BRW",
    terminals: [
      {
        id: 263,
        name: "Muslim Movers Burewala Stop",
        latitude: null,
        longitude: null,
        address: "Chohan Terminal Burewala",
        short_code: "BRW-MM",
        city_code: "BRW",
        city: "Burewala",
      },
    ],
  },
  {
    id: 99,
    name: "Dunyapur",
    short_code: "DNY",
    terminals: [
      {
        id: 268,
        name: "GENRAL BUS STAND FAISAL MOVERS",
        latitude: null,
        longitude: null,
        address: "General Bus Stand Faisal Movers",
        short_code: "DNY-GBS",
        city_code: "DNY",
        city: "Dunyapur",
      },
    ],
  },
  {
    id: 1,
    name: "Lahore (لاہور)",
    short_code: "LHE",
    terminals: [
      {
        id: 237,
        name: "Lahore Thokar Jinnah Terminal",
        latitude: null,
        longitude: null,
        address: "Faisal Movers Jinnah Terminal, Thokar, Lahore",
        short_code: "LHE-TKN",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 144,
        name: "City Terminal Lahore",
        latitude: null,
        longitude: null,
        address: "Lahore City Bus Terminal, Near Yateem Khana Chowk",
        short_code: "LHE-CT",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 194,
        name: "Mall Road Lahore",
        latitude: null,
        longitude: null,
        address: "Mall Road, Gulberg, Lahore",
        short_code: "LHE-MR",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 183,
        name: "Lahore Rehber Bus Terminal",
        latitude: null,
        longitude: null,
        address:
          "Opposite Govt City Distt Bus Terminal Near Chowk Yateem Khana",
        short_code: "LHE-FMB",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 163,
        name: "Lahore Bakar Mandi",
        latitude: null,
        longitude: null,
        address: "Band Rd, Shera Kot",
        short_code: "LHE-BM",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 143,
        name: "Kainat Travels Terminal Lahore",
        latitude: null,
        longitude: null,
        address: "-",
        short_code: "LHE-KTT",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 213,
        name: "Sadabahar Daewoo Lahore",
        latitude: 31.594098625942667,
        longitude: 74.31737604232927,
        address: "Badami Bagh, Lari Adda, Near Minar-e- Pakistan",
        short_code: "LHE-SAD",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 285,
        name: "CB General Bus Stand",
        latitude: null,
        longitude: null,
        address: " General Bus Stand # 14 Badami Bagh Lari Adda Lahore",
        short_code: "LHE-GBS",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 286,
        name: "CB Alliance Travel Chakwal City",
        latitude: null,
        longitude: null,
        address: "Alliance Travel Chakwal City",
        short_code: "LHE-CHK",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 246,
        name: "General Bus Stand LHR",
        latitude: null,
        longitude: null,
        address:
          "(Via GT Road) Madina Chowk Near Mani Paan Shop General Bus Stand Badami Bagh Lari Adda Lahore",
        short_code: "LHE-NFC",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 1,
        name: "Lahore Thokar",
        latitude: null,
        longitude: null,
        address:
          "Thokar Niaz Baig, Between Multan Road & Mohlanwal Road, Near PSO Petrol Pump",
        short_code: "LHE",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 243,
        name: "Lahore Thokar Terminal Muslim Movers",
        latitude: null,
        longitude: null,
        address: "Jinnah Terminal Near Thokar Niaz Baig Bypass Lahore",
        short_code: "LHE-TKR",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 245,
        name: "Skyways Terminal Lahore",
        latitude: null,
        longitude: null,
        address: "Skyways Terminal  Near Yateem Khana Band Road Lahore",
        short_code: "LHE-SKY",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 258,
        name: "Abdullah Terminal Sania Express Lahore",
        latitude: null,
        longitude: null,
        address:
          "Abdullah Terminal Sania Express Near Yateem Khana Band Road Lahore",
        short_code: "LHE-ATSE",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 79,
        name: "LAHORE DHA",
        latitude: null,
        longitude: null,
        address: "Plot #432/1, Sector-L, Phase V, DHA, Near LGS,",
        short_code: "LHE-DHA",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
      {
        id: 105,
        name: "LAHORE KALMA CHOWK",
        latitude: null,
        longitude: null,
        address: "Kalma Chowk",
        short_code: "LHE-KC",
        city_code: "LHE",
        city: "Lahore (لاہور)",
      },
    ],
  },
  {
    id: 2,
    name: "Rawalpindi / Islamabad (اسلام آباد)",
    short_code: "RWP",
    terminals: [
      {
        id: 136,
        name: "Karachi Travel Point Rawalpindi",
        latitude: null,
        longitude: null,
        address: "Near Post Office Pirwadhai Rawalpindi",
        short_code: "RWP-KTP",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 146,
        name: "Rawalpindi Terminal",
        latitude: null,
        longitude: null,
        address: "Pirwadhai Mor, Near Peshawar Road",
        short_code: "RWP-PT",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 141,
        name: "Pirwadhai Rawalpindi",
        latitude: null,
        longitude: null,
        address: "Stand No 6, Near Police Station, Pirwadhai",
        short_code: "RWP-PR",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 147,
        name: "Kainat Travels Terminal Rawalpindi",
        latitude: 33.61384424015015,
        longitude: 72.99661261504018,
        address: "Pirwadhai Mor, Near Peshawar Road",
        short_code: "RWP-NK",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 173,
        name: "Rawalpindi",
        latitude: null,
        longitude: null,
        address:
          "Sania Express Furnteir Panjab Bus Terminal Near i8 Traffic Signal Islamabad, Faisal Movers City Bus.",
        short_code: "RWP-FM",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 155,
        name: "Rawalpindi Sadar Office",
        latitude: null,
        longitude: null,
        address:
          "Aurangzeb Hotel, Police Station Road, Near Railway Station Sadar Rawalpindi Cantt",
        short_code: "RWP-SO",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 154,
        name: "Peshawar Road Rawalpindi",
        latitude: null,
        longitude: null,
        address: "Main Pirwadhai Mor, Peshawar Road Rawalpindi",
        short_code: "RWP-AB",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 145,
        name: "Kainat Travels Rawalpindi",
        latitude: null,
        longitude: null,
        address: "Main Pirwadhai General Bus Stand",
        short_code: "RWP-KP",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 276,
        name: "Adil Express Terminal Peerwadhai Mour Rawalpindi",
        latitude: null,
        longitude: null,
        address:
          "Adil Express Terminal Peerwadhai Mour, City District Government Adda Rawalpindi. ",
        short_code: "RWP-ATPM",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 212,
        name: "Sadabahar Rawalpindi Adda",
        latitude: 33.63038409612292,
        longitude: 73.04102571349391,
        address: "Pir Wadahi Main Bus Stand Number 35",
        short_code: "RWP-SAD",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 214,
        name: "Sadabahar Islamabad Adda",
        latitude: 33.68905891072095,
        longitude: 73.03250845229252,
        address: "Karachi Company, G9 Markaz",
        short_code: "RWP-SIA",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 283,
        name: "Peer Wadhai Mour MantharTerminal",
        latitude: null,
        longitude: null,
        address:
          "Shop 60, Pirwadhai Bus Stand, Pirwadhai, Pirwadhai, Rawalpindi, Punjab 46000",
        short_code: "RWP-PW",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 290,
        name: "Rawalpindi 26 no Chungi Pin",
        latitude: null,
        longitude: null,
        address: "Rawalpindi 26 no Chungi Pin",
        short_code: "RWP-CG",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 184,
        name: "FMBT Islamabad",
        latitude: null,
        longitude: null,
        address:
          "FMBT Express  Blue Line Bus Terminal, Near i-8 Traffic Signal, Faizabad, Islamabad",
        short_code: "RWP-FMB",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 22,
        name: "RAWALPINDI",
        latitude: null,
        longitude: null,
        address:
          "Deawoo Terminal Rawalpindi, Jhangi Sayyedan, Near EME College. No 26 Chungi Peshawar Road",
        short_code: "RWP-MAIN",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 123,
        name: "RAWALPINDI (FAIZABAD)",
        latitude: null,
        longitude: null,
        address:
          "Shop # 2, Ground Floor, Sultan Arcade, Sector I-8/4, Faizabad I 8/4 Islamabad",
        short_code: "RWP-FZB",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 247,
        name: "Islamabad Larri Adda",
        latitude: null,
        longitude: null,
        address: "Karachi company G9 markaz",
        short_code: "RWP-KC",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 260,
        name: "Punjab Frontier Terminal Islamabad",
        latitude: null,
        longitude: null,
        address:
          "Punjab Frontier Terminal Opposite Skyways Terminal Faizabad Islambad",
        short_code: "RWP-NFC",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 265,
        name: "Shalimar Terminal Rawalpindi",
        latitude: null,
        longitude: null,
        address: "Shalimar Terminal Pirwadhai, Rawalpindi",
        short_code: "RWP-STP",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 272,
        name: "Rawalpindi Kohistan Terminal",
        latitude: null,
        longitude: null,
        address: "Kohistan Terminal Peerwadhai Mour",
        short_code: "RWP-PMP",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
      {
        id: 271,
        name: "Rawalpindi Raja Travel Terminal",
        latitude: null,
        longitude: null,
        address:
          "Faisal Movers City Bus Terminal Jhangi Sayyedan 26No Chungi Rawalpindi.",
        short_code: "RWP-RTT",
        city_code: "RWP",
        city: "Rawalpindi / Islamabad (اسلام آباد)",
      },
    ],
  },
  {
    id: 3,
    name: "Batkhela (بٹ خیلہ)",
    short_code: "BATK",
    terminals: [
      {
        id: 26,
        name: "BATKHELA",
        latitude: null,
        longitude: null,
        address: "Shahibzada Markete, Near Main Haji Baba Chowk, GT. Road",
        short_code: "BATK",
        city_code: "BATK",
        city: "Batkhela (بٹ خیلہ)",
      },
    ],
  },
  {
    id: 4,
    name: "Bhakkar (بھکر)",
    short_code: "BHK",
    terminals: [
      {
        id: 295,
        name: "Main Lari Adda",
        latitude: null,
        longitude: null,
        address: "Main Lari Adda near Gate lari Adda",
        short_code: "BHK-LA",
        city_code: "BHK",
        city: "Bhakkar (بھکر)",
      },
      {
        id: 19,
        name: "BHAKKAR",
        latitude: null,
        longitude: null,
        address:
          "Opposite General Bus stand Jhang Road, Chak No.34/B TDA, Tehsil & District Bhakkar",
        short_code: "BHK",
        city_code: "BHK",
        city: "Bhakkar (بھکر)",
      },
    ],
  },
  {
    id: 5,
    name: "Gujrat (گجرات)",
    short_code: "GJT",
    terminals: [
      {
        id: 229,
        name: "Genral Bus Stand Gujrat",
        latitude: null,
        longitude: null,
        address: "Lari Adda Natt Coach",
        short_code: "GJT-GBS",
        city_code: "GJT",
        city: "Gujrat (گجرات)",
      },
      {
        id: 33,
        name: "GUJRAT",
        latitude: null,
        longitude: null,
        address: "Khasra no. 714, Khatooni no. 665/1208, GT Road Near UBL Bank",
        short_code: "GJT",
        city_code: "GJT",
        city: "Gujrat (گجرات)",
      },
    ],
  },
  {
    id: 6,
    name: "Hyderabad (حیدرآباد)",
    short_code: "HYD",
    terminals: [
      {
        id: 164,
        name: "Hyderabad City Terminal",
        latitude: null,
        longitude: null,
        address: "Badin Stop",
        short_code: "HYD-BS",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
      {
        id: 135,
        name: "Kainat Travels Terminal Hyderabad",
        latitude: null,
        longitude: null,
        address: "National Highway 5, Adjacent to Ayub Hotel",
        short_code: "HYD-KTT",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
      {
        id: 165,
        name: "Main Hyderabad Terminal",
        latitude: null,
        longitude: null,
        address: "Citizen Colony, Opposite Rajputana Hospital Qasimabad",
        short_code: "HYD-CC",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
      {
        id: 284,
        name: "Hyderabad Ayub Hotel",
        latitude: null,
        longitude: null,
        address: "Hyderabad Ayub Hotel",
        short_code: "HYD-AH",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
      {
        id: 12,
        name: "HYDERABAD",
        latitude: null,
        longitude: null,
        address: "Hyderabad Bypass",
        short_code: "HYD",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
      {
        id: 113,
        name: "HYDERABAD CITY",
        latitude: null,
        longitude: null,
        address: "N/A",
        short_code: "HYD-CITY",
        city_code: "HYD",
        city: "Hyderabad (حیدرآباد)",
      },
    ],
  },
  {
    id: 7,
    name: "Mianwali (میانوالی)",
    short_code: "MNW",
    terminals: [
      {
        id: 29,
        name: "MIANWALI",
        latitude: null,
        longitude: null,
        address: "PAF Road, Near Flavor City Hotel",
        short_code: "MNW",
        city_code: "MNW",
        city: "Mianwali (میانوالی)",
      },
    ],
  },
  {
    id: 8,
    name: "Moro (مورو)",
    short_code: "MOR",
    terminals: [
      {
        id: 11,
        name: "MORO",
        latitude: null,
        longitude: null,
        address: "Byco Falak Filling Station, Bypass Road, NHA, Moro.",
        short_code: "MOR",
        city_code: "MOR",
        city: "Moro (مورو)",
      },
    ],
  },
  {
    id: 9,
    name: "Murree (مری)",
    short_code: "MUR",
    terminals: [
      {
        id: 189,
        name: "Nathia Gali, Murree",
        latitude: null,
        longitude: null,
        address: "Murree Nathia Gali",
        short_code: "MUR-NG",
        city_code: "MUR",
        city: "Murree (مری)",
      },
      {
        id: 185,
        name: "Murree",
        latitude: null,
        longitude: null,
        address:
          "Main General Bus Stand Faisal Movers Bus Terminal Upper Mall Road",
        short_code: "MUR-FMB",
        city_code: "MUR",
        city: "Murree (مری)",
      },
      {
        id: 35,
        name: "MURREE",
        latitude: null,
        longitude: null,
        address:
          "Shop No. 14, 21, 22 Cart Road, Cantonment Plaza, Frida Market, Cantt",
        short_code: "MUR",
        city_code: "MUR",
        city: "Murree (مری)",
      },
    ],
  },
  {
    id: 10,
    name: "Bhalwal (بهلوال)",
    short_code: "BHL",
    terminals: [
      {
        id: 40,
        name: "BHALWAL",
        latitude: null,
        longitude: null,
        address:
          "Near General Bus Stand, Chak No. 8, North Bhalwal City Road, Tehsil Bhalwal, Dist. Sargodha",
        short_code: "BHL",
        city_code: "BHL",
        city: "Bhalwal (بهلوال)",
      },
    ],
  },
  {
    id: 11,
    name: "Rahim Yar Khan (رحیم یار خان)",
    short_code: "RYK",
    terminals: [
      {
        id: 8,
        name: "Chowk Bahadurpur Rahim Yar Khan",
        latitude: null,
        longitude: null,
        address:
          "Moza Bahadurpur, KLP Road , District Rahim Yar Khan, Chowk Bahadupur",
        short_code: "CHBDR",
        city_code: "RYK",
        city: "Rahim Yar Khan (رحیم یار خان)",
      },
      {
        id: 293,
        name: "Thali chowk terminal",
        latitude: null,
        longitude: null,
        address: "Rahim yar Khan, Near Thali chowk",
        short_code: "RYK-RYK",
        city_code: "RYK",
        city: "Rahim Yar Khan (رحیم یار خان)",
      },
      {
        id: 128,
        name: "Rahim Yar Khan",
        latitude: null,
        longitude: null,
        address: "Iqbalabad",
        short_code: "IQB",
        city_code: "RYK",
        city: "Rahim Yar Khan (رحیم یار خان)",
      },
    ],
  },
  {
    id: 12,
    name: "Swat (سوات)",
    short_code: "SWT",
    terminals: [
      {
        id: 71,
        name: "BARIKOT",
        latitude: null,
        longitude: null,
        address: "Opp. Government Higher Secondary School, G.T. Road, Barikot",
        short_code: "BRK",
        city_code: "SWT",
        city: "Swat (سوات)",
      },
      {
        id: 27,
        name: "SWAT",
        latitude: null,
        longitude: null,
        address:
          "Daewoo Express Bus Service Ingaro Dheri Chowk Takhta Band Road Swat",
        short_code: "SWT",
        city_code: "SWT",
        city: "Swat (سوات)",
      },
      {
        id: 228,
        name: "Swat",
        latitude: null,
        longitude: null,
        address: "Pizagat Shahid Coach Terminal",
        short_code: "SWT-GBS",
        city_code: "SWT",
        city: "Swat (سوات)",
      },
    ],
  },
  {
    id: 13,
    name: "Chakwal (چکوال)",
    short_code: "CHK",
    terminals: [
      {
        id: 273,
        name: "CB Alliance Travel Chakwal",
        latitude: null,
        longitude: null,
        address: "Alliance Travel Chakwal City",
        short_code: "CHK-ATC",
        city_code: "CHK",
        city: "Chakwal (چکوال)",
      },
      {
        id: 282,
        name: "Adil Express Terminal Chakwal",
        latitude: null,
        longitude: null,
        address: "Adil Express Terminal Chakwal",
        short_code: "CHK-AET",
        city_code: "CHK",
        city: "Chakwal (چکوال)",
      },
    ],
  },
  {
    id: 14,
    name: "Sakrand (سکرنڈ)",
    short_code: "SKR",
    terminals: [
      {
        id: 117,
        name: "SAKRAND",
        latitude: null,
        longitude: null,
        address: "N/A",
        short_code: "SKR",
        city_code: "SKR",
        city: "Sakrand (سکرنڈ)",
      },
    ],
  },
  {
    id: 15,
    name: "Haripur (ہری پور)",
    short_code: "HRP",
    terminals: [
      {
        id: 277,
        name: "Hazara Movers Haripur Interchange",
        latitude: null,
        longitude: null,
        address: "Shah Maqsood Interchange Haripur.",
        short_code: "HRP-SMI",
        city_code: "HRP",
        city: "Haripur (ہری پور)",
      },
      {
        id: 291,
        name: "Haripur Terminal Interchange",
        latitude: null,
        longitude: null,
        address: "Haripur Terminal Interchange",
        short_code: "HRP-SSI",
        city_code: "HRP",
        city: "Haripur (ہری پور)",
      },
      {
        id: 119,
        name: "Shah Maqsood Haripur",
        latitude: null,
        longitude: null,
        address:
          "Daewoo Express Shah Maqsood, Near Shah Maqsood Interchange, Hazara Motorway",
        short_code: "SHMQ",
        city_code: "HRP",
        city: "Haripur (ہری پور)",
      },
    ],
  },
  {
    id: 16,
    name: "Faisalabad (فیصل آباد)",
    short_code: "FSB",
    terminals: [
      {
        id: 150,
        name: "Kainat Travels Faisalabad",
        latitude: 31.415930375845807,
        longitude: 73.09132657995382,
        address: "GTS Chowk Faisalabad",
        short_code: "FSB-KTO",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 186,
        name: "Faisalabad Kohistan Express Bus Terminal",
        latitude: null,
        longitude: null,
        address: "Kohistan Express Bus Terminal near GTS.",
        short_code: "FSB-KE",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 178,
        name: "Faisalabad",
        latitude: null,
        longitude: null,
        address: "Motorway Interchange, Faisalabad",
        short_code: "FSB-FM",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 152,
        name: "Taimoor Terminal Faisalabad",
        latitude: null,
        longitude: null,
        address: "GTS Chowk",
        short_code: "FSB-TT",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 148,
        name: "Al-Halal Faisalabad",
        latitude: null,
        longitude: null,
        address: "Al-Halal Travels Allied Mor Sargodha Road",
        short_code: "FSB-AH",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 281,
        name: "Faisalabad Interchange Sargodha",
        latitude: null,
        longitude: null,
        address: " Faisalabad Interchange Sargodha Road",
        short_code: "FSB-FIS",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 16,
        name: "FAISALABAD",
        latitude: null,
        longitude: null,
        address:
          "Chak No-123 (JB) Mohallah Akbarabad, Punj Pullian Road, Opp. Allied Hospital",
        short_code: "FSB",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
      {
        id: 227,
        name: "Subhan Adda Faisalabad",
        latitude: null,
        longitude: null,
        address: "New Subhan Adda Near Railway Station",
        short_code: "FSB-RS",
        city_code: "FSB",
        city: "Faisalabad (فیصل آباد)",
      },
    ],
  },
  {
    id: 17,
    name: "Chichawatni (چیچہ وطنی)",
    short_code: "CHCW",
    terminals: [
      {
        id: 244,
        name: "Muslim Movers stop Chichawatni",
        latitude: null,
        longitude: null,
        address: "Faisal Movers Terminal Chichawatni",
        short_code: "CHCW-MM",
        city_code: "CHCW",
        city: "Chichawatni (چیچہ وطنی)",
      },
      {
        id: 125,
        name: "CHICHAWATNI",
        latitude: null,
        longitude: null,
        address:
          "Daewoo Express, bypass Road, near Al Ghani Chowk, Nazir Town Nazeer Town",
        short_code: "CHCW",
        city_code: "CHCW",
        city: "Chichawatni (چیچہ وطنی)",
      },
    ],
  },
  {
    id: 18,
    name: "Muzafargarh (مظفر گڑھ)",
    short_code: "MUZF",
    terminals: [
      {
        id: 61,
        name: "MUZAFARGARH",
        latitude: null,
        longitude: null,
        address: "Dera Ghazi Khan Road, Thal Jute Mills",
        short_code: "MUZF",
        city_code: "MUZF",
        city: "Muzafargarh (مظفر گڑھ)",
      },
      {
        id: 88,
        name: "Muzafargarh",
        latitude: null,
        longitude: null,
        address: "Chowk Qureshi",
        short_code: "CHKQ",
        city_code: "MUZF",
        city: "Muzafargarh (مظفر گڑھ)",
      },
    ],
  },
  {
    id: 19,
    name: "Mian Chanu (مِياں چنُّوں)",
    short_code: "MCHN",
    terminals: [
      {
        id: 126,
        name: "MIAN CHANU",
        latitude: null,
        longitude: null,
        address: "N/A",
        short_code: "MCHN",
        city_code: "MCHN",
        city: "Mian Chanu (مِياں چنُّوں)",
      },
    ],
  },
  {
    id: 20,
    name: "Multan (ملتان)",
    short_code: "MUL",
    terminals: [
      {
        id: 142,
        name: "Kainat Travel Multan",
        latitude: 30.175122738118734,
        longitude: 71.50995562048608,
        address:
          "Booking Office #1, Stand #18, New AC Terminal General Bus Stand",
        short_code: "MUL-GBS",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
      {
        id: 138,
        name: "Multan",
        latitude: null,
        longitude: null,
        address: "Madina Flying Coach Bus Terminal, Vehari Chowk",
        short_code: "MUL-W",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
      {
        id: 278,
        name: "Shah Shamas Tabraiz Interchange Multan",
        latitude: null,
        longitude: null,
        address: "Shah Shamas Tabraiz Interchange Multan",
        short_code: "MUL-STIM",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
      {
        id: 226,
        name: "Multan Vehari Chowk",
        latitude: null,
        longitude: null,
        address: "Vehari Chowk Madina Flying Coaches",
        short_code: "MUL-BS",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
      {
        id: 253,
        name: "Bilal Travel MultanAdda",
        latitude: null,
        longitude: null,
        address: "Bilal Travels wains plaza Veharhi chok Multan",
        short_code: "MUL-BTVC",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
      {
        id: 5,
        name: "Multan (Main)",
        latitude: null,
        longitude: null,
        address: "TTC Khanewal Road, Gaddafi Chowk",
        short_code: "MUL",
        city_code: "MUL",
        city: "Multan (ملتان)",
      },
    ],
  },
  {
    id: 21,
    name: "Sargodha (سرگودھا)",
    short_code: "SGH",
    terminals: [
      {
        id: 82,
        name: "Sargodha",
        latitude: null,
        longitude: null,
        address: "Salam Interchange",
        short_code: "SAIT",
        city_code: "SGH",
        city: "Sargodha (سرگودھا)",
      },
      {
        id: 224,
        name: "General Bus Stand Sargodha",
        latitude: null,
        longitude: null,
        address: "Lari Adda Stand Number 17",
        short_code: "SGH-GBS",
        city_code: "SGH",
        city: "Sargodha (سرگودھا)",
      },
      {
        id: 21,
        name: "SARGODHA",
        latitude: null,
        longitude: null,
        address:
          "Plot No. 149 & 150, Main College Road, Wagon Stand, Chak No. 47 NB, Sargodha Cantt",
        short_code: "SGH",
        city_code: "SGH",
        city: "Sargodha (سرگودھا)",
      },
    ],
  },
  {
    id: 22,
    name: "Nowshera (نوشہرہ)",
    short_code: "NOW",
    terminals: [
      {
        id: 23,
        name: "NOWSHERA",
        latitude: null,
        longitude: null,
        address:
          "Army Welfare Shops, CMH, The Mall, G.T Road, Station Headquarter",
        short_code: "NWSH",
        city_code: "NOW",
        city: "Nowshera (نوشہرہ)",
      },
    ],
  },
  {
    id: 23,
    name: "Jhang (جھنگ)",
    short_code: "JHA",
    terminals: [
      {
        id: 17,
        name: "JHANG",
        latitude: null,
        longitude: null,
        address: "Safdar Petrolium, Mohallah Islam Nagar, Bhukkar Road",
        short_code: "JHA",
        city_code: "JHA",
        city: "Jhang (جھنگ)",
      },
    ],
  },
  {
    id: 24,
    name: "Jhelum (جہلم)",
    short_code: "JHEL",
    terminals: [
      {
        id: 241,
        name: "Lahore Morr Jehlum Cantt",
        latitude: null,
        longitude: null,
        address: "Lahore Morr, Jhelum Cantt, Jhelum",
        short_code: "JHEL-LM",
        city_code: "JHEL",
        city: "Jhelum (جہلم)",
      },
      {
        id: 53,
        name: "JHELUM",
        latitude: null,
        longitude: null,
        address: "Behind Police Welfare Pump, Main G.T Road, Jada",
        short_code: "JHEL",
        city_code: "JHEL",
        city: "Jhelum (جہلم)",
      },
    ],
  },
  {
    id: 25,
    name: "Lodhran (لودھراں)",
    short_code: "LDH",
    terminals: [
      {
        id: 121,
        name: "LODHRAN",
        latitude: null,
        longitude: null,
        address: "Gourmet Rd, Mahram Wala Lodhran",
        short_code: "LHD",
        city_code: "LDH",
        city: "Lodhran (لودھراں)",
      },
      {
        id: 269,
        name: "MELAD CHOWK FAISAL MOVERS",
        latitude: null,
        longitude: null,
        address: "Melad Chowk Faisal Movers",
        short_code: "LDH-MCFM",
        city_code: "LDH",
        city: "Lodhran (لودھراں)",
      },
      {
        id: 129,
        name: "Lodhran",
        latitude: null,
        longitude: null,
        address: "Kahror Chowk, Kahror Pakka Road",
        short_code: "DNY",
        city_code: "LDH",
        city: "Lodhran (لودھراں)",
      },
    ],
  },
  {
    id: 26,
    name: "Abbottabad (ایبٹ آباد)",
    short_code: "ABT",
    terminals: [
      {
        id: 134,
        name: "Abbotabad",
        latitude: null,
        longitude: null,
        address: "Fawara Chowk",
        short_code: "ABT-FWCHK",
        city_code: "ABT",
        city: "Abbottabad (ایبٹ آباد)",
      },
      {
        id: 36,
        name: "ABBOTTABAD",
        latitude: null,
        longitude: null,
        address:
          "Near Mesile Chowk, Moza Jhangi, Chowk Mandian, Main Mansehra Road, Abt Cantt",
        short_code: "ABT",
        city_code: "ABT",
        city: "Abbottabad (ایبٹ آباد)",
      },
      {
        id: 235,
        name: "Abbottabad",
        latitude: null,
        longitude: null,
        address: "Fawara chowk",
        short_code: "ABT-FC",
        city_code: "ABT",
        city: "Abbottabad (ایبٹ آباد)",
      },
      {
        id: 254,
        name: "Abbottabad Interchange",
        latitude: null,
        longitude: null,
        address: "Havelian Interchange Abbottabad",
        short_code: "ABT-HM",
        city_code: "ABT",
        city: "Abbottabad (ایبٹ آباد)",
      },
    ],
  },
  {
    id: 27,
    name: "Jahanian (جہانیاں)",
    short_code: "JHNN",
    terminals: [
      {
        id: 127,
        name: "JAHANIAN",
        latitude: null,
        longitude: null,
        address: "Lodhran - Khanewal Expressway",
        short_code: "JHNN",
        city_code: "JHNN",
        city: "Jahanian (جہانیاں)",
      },
      {
        id: 267,
        name: "JAHANIAN GENRAL BUS STAND FAISAL MOVERS",
        latitude: null,
        longitude: null,
        address: "General Bus Stand Faisal Movers Near Graveyard",
        short_code: "JHNN-GBS",
        city_code: "JHNN",
        city: "Jahanian (جہانیاں)",
      },
    ],
  },
  {
    id: 28,
    name: "Zahirpir (ظاہرپیر)",
    short_code: "ZHI",
    terminals: [
      {
        id: 130,
        name: "ZAHIRPIR CITY",
        latitude: null,
        longitude: null,
        address: "Kot Mithan Road, Zāhir Pīr, Rahim Yar Khan",
        short_code: "ZHC",
        city_code: "ZHI",
        city: "Zahirpir (ظاہرپیر)",
      },
      {
        id: 131,
        name: "Zahirpir",
        latitude: null,
        longitude: null,
        address: "Zahirpir Interchange",
        short_code: "ZHI",
        city_code: "ZHI",
        city: "Zahirpir (ظاہرپیر)",
      },
    ],
  },
  {
    id: 29,
    name: "Karachi (کراچی)",
    short_code: "KHI",
    terminals: [
      {
        id: 196,
        name: "Al Asif Karachi",
        latitude: 24.945094527788587,
        longitude: 67.08570872883536,
        address: "Al Asif Karachi",
        short_code: "KHI-AAS",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 140,
        name: "Baldia Karachi",
        latitude: null,
        longitude: null,
        address: "NULL",
        short_code: "KHI-BD",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 191,
        name: "Kemari Yousuf Goth Karachi",
        latitude: null,
        longitude: null,
        address: "Main Bus Stand of Kemari Yousuf Goth",
        short_code: "KHI-KEM",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 139,
        name: "Saddar Karachi",
        latitude: null,
        longitude: null,
        address: "MA Jinnah Road Taj Complex Saddar",
        short_code: "KHI-MA",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 204,
        name: "Karachi Al Asif",
        latitude: 24.95103643134568,
        longitude: 67.09214057116463,
        address: "Al Asif Square, Sohrab Goth, Quetta Bus Terminal",
        short_code: "KHI-QTA",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 210,
        name: "Karachi Makka Coach Terminal",
        latitude: 24.84536764314546,
        longitude: 67.0378881208841,
        address:
          "Makka Coach by Waqas Warraich Opposite Total Petrol Pump Nearby Karachi Cantt Station",
        short_code: "KHI-CS",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 279,
        name: "Adil Express Sohrab Goth Karachi",
        latitude: null,
        longitude: null,
        address: "Karachi Bus Terminal Sohrab Goth.",
        short_code: "KHI-SGK",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 280,
        name: "Adil Express Taj Complex",
        latitude: null,
        longitude: null,
        address: "Taj complex adil express terminal",
        short_code: "KHI-TCAE",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 287,
        name: "Taj Complex  Terminal",
        latitude: null,
        longitude: null,
        address:
          "Taj Medical Complex, M.A Jinnah Rd, Central Jacob Lines Karachi, Karachi City, Sindh 74400, Pakistan",
        short_code: "KHI-TC",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 275,
        name: "Sohrab Goth Terminal",
        latitude: null,
        longitude: null,
        address:
          "Al Asif New Bus Terminal, Sector 1 B Gulzar E Hijri Scheme 33",
        short_code: "KHI-SG",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 289,
        name: "Patel Para",
        latitude: null,
        longitude: null,
        address: "Bilal Travels Patel Para Karachi Terminal",
        short_code: "KHI-PP",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 13,
        name: "KARACHI",
        latitude: null,
        longitude: null,
        address:
          "Scheme #33, Main Super Highway, Near PSO Petrol Pump, Sohrab Goth",
        short_code: "KHI-MAIN",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 197,
        name: "Sachal Goth Karachi",
        latitude: 24.951046721292105,
        longitude: 67.12853958465855,
        address:
          "Near Kiran Hospital Road, Serena Village Shop #3, Near Mehran Lawn, Sector 34B, Scheme 33 Sachal Goth",
        short_code: "KHI-SACH",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 122,
        name: "KARACHI CANTT",
        latitude: null,
        longitude: null,
        address: "Cantt, Karachi",
        short_code: "KHI-CNT",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 251,
        name: "Al Imdad Saddar Stop",
        latitude: null,
        longitude: null,
        address: "Burhan center quetta adda saddar",
        short_code: "KHI-SAD",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 264,
        name: "Nooriabad Karachi",
        latitude: null,
        longitude: null,
        address: "Nooriabad Interchange, Karachi",
        short_code: "KHI-NB",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
      {
        id: 120,
        name: "KARACHI AL-ASIF",
        latitude: null,
        longitude: null,
        address: "Al Asif, Karachi",
        short_code: "KHI-ASIF",
        city_code: "KHI",
        city: "Karachi (کراچی)",
      },
    ],
  },
  {
    id: 30,
    name: "Ahmed Pur (احمد پور)",
    short_code: "APE",
    terminals: [
      {
        id: 63,
        name: "AHMED PUR EAST",
        latitude: null,
        longitude: null,
        address: "Food Club, Ahmedpur Petroleum Station, Near Toll Plaza",
        short_code: "APE",
        city_code: "APE",
        city: "Ahmed Pur (احمد پور)",
      },
    ],
  },
  {
    id: 31,
    name: "Bahawalpur (بہاولپور)",
    short_code: "BAH",
    terminals: [
      {
        id: 6,
        name: "BAHAWALPUR",
        latitude: null,
        longitude: null,
        address:
          "Opp. Sadiq Public School, Ahmed Pur Road, Dera Nawab Sahib Road, Near NLC",
        short_code: "BAH",
        city_code: "BAH",
        city: "Bahawalpur (بہاولپور)",
      },
      {
        id: 270,
        name: "Bahawalpur Faisal Mover Terminal",
        latitude: null,
        longitude: null,
        address: "General AC Bus Terminal, opposite Army PSO Pump, Bahawalpur.",
        short_code: "BAH-FM",
        city_code: "BAH",
        city: "Bahawalpur (بہاولپور)",
      },
      {
        id: 288,
        name: "Bahawalpur AC bus stand",
        latitude: null,
        longitude: null,
        address: "General AC Bus Terminal, opposite Army PSO Pump, Bahawalpur.",
        short_code: "BAH-ACBT",
        city_code: "BAH",
        city: "Bahawalpur (بہاولپور)",
      },
    ],
  },
  {
    id: 32,
    name: "Daska (ڈسکہ)",
    short_code: "DSK",
    terminals: [
      {
        id: 59,
        name: "DASKA",
        latitude: null,
        longitude: null,
        address: "Gujranwala, Opposite Star CNG, Near Canal Bridge",
        short_code: "DSK",
        city_code: "DSK",
        city: "Daska (ڈسکہ)",
      },
    ],
  },
  {
    id: 33,
    name: "Dera Ghazi Khan (ڈیرہ غازی خان)",
    short_code: "DGK",
    terminals: [
      {
        id: 168,
        name: "Faisal Movers Bus Terminal, Dera Ghazi Khan",
        latitude: null,
        longitude: null,
        address: "Afridi Bazar, Pyary Wala Pul",
        short_code: "DGK-AB",
        city_code: "DGK",
        city: "Dera Ghazi Khan (ڈیرہ غازی خان)",
      },
      {
        id: 221,
        name: "City Linker Bus Stand DG Khan",
        latitude: null,
        longitude: null,
        address: "Pyaare Wala Pull City Linkers DG Khan",
        short_code: "DGK-PWP",
        city_code: "DGK",
        city: "Dera Ghazi Khan (ڈیرہ غازی خان)",
      },
      {
        id: 14,
        name: "DERA GHAZI KHAN",
        latitude: null,
        longitude: null,
        address: "Moza Ghadai Shumali, Near New General Bus Stand",
        short_code: "DGKH",
        city_code: "DGK",
        city: "Dera Ghazi Khan (ڈیرہ غازی خان)",
      },
    ],
  },
  {
    id: 34,
    name: "Dera Ismail Khan (ڈیرہ اسماعیل خان)",
    short_code: "DIK",
    terminals: [
      {
        id: 219,
        name: "Dera Ismail Khan",
        latitude: null,
        longitude: null,
        address: "New Khan Terminal Circular Road, Near State Life Building",
        short_code: "DIK-NKT",
        city_code: "DIK",
        city: "Dera Ismail Khan (ڈیرہ اسماعیل خان)",
      },
      {
        id: 20,
        name: "DERA ISMAIL KHAN",
        latitude: null,
        longitude: null,
        address: "Opp. Khan Plaza, Bannu Road",
        short_code: "DIKH",
        city_code: "DIK",
        city: "Dera Ismail Khan (ڈیرہ اسماعیل خان)",
      },
    ],
  },
  {
    id: 35,
    name: "Dharki (ڈھرکی)",
    short_code: "DHR",
    terminals: [
      {
        id: 48,
        name: "DHARKI",
        latitude: null,
        longitude: null,
        address: "Sattar CNG, Bypass Road, Daharki Distt. Ghotki",
        short_code: "DHR",
        city_code: "DHR",
        city: "Dharki (ڈھرکی)",
      },
    ],
  },
  {
    id: 36,
    name: "Khan Pur (خان پور)",
    short_code: "KPR",
    terminals: [
      {
        id: 292,
        name: "Allah Khyer chowk terminal",
        latitude: null,
        longitude: null,
        address: "Allah khyer chowk/Nawakot Chowk",
        short_code: "KPR-AKC",
        city_code: "KPR",
        city: "Khan Pur (خان پور)",
      },
      {
        id: 75,
        name: "KHAN PUR",
        latitude: null,
        longitude: null,
        address: "Attock Petroleum, Quaid-e-Millat Road Bypass",
        short_code: "KPUR",
        city_code: "KPR",
        city: "Khan Pur (خان پور)",
      },
    ],
  },
  {
    id: 37,
    name: "Khanewal (خانیوال)",
    short_code: "KHW",
    terminals: [
      {
        id: 266,
        name: "MAIN LAHORE MORE MULTAN",
        latitude: null,
        longitude: null,
        address: "Main Lahore Mor Multan G.T Road Faisal Movers Khanewal",
        short_code: "KHW-MLMM",
        city_code: "KHW",
        city: "Khanewal (خانیوال)",
      },
      {
        id: 4,
        name: "Khanewal",
        latitude: null,
        longitude: null,
        address:
          "Daewoo Express Khanewal, Lahore Morr, Khanewal-Kabirwala Road",
        short_code: "KHW",
        city_code: "KHW",
        city: "Khanewal (خانیوال)",
      },
    ],
  },
  {
    id: 38,
    name: "Kohat (کوہاٹ)",
    short_code: "KHT",
    terminals: [
      {
        id: 274,
        name: "Kohat University Chowk",
        latitude: null,
        longitude: null,
        address: "Kohat University Chowk",
        short_code: "KHT-UC",
        city_code: "KHT",
        city: "Kohat (کوہاٹ)",
      },
      {
        id: 39,
        name: "KOHAT",
        latitude: null,
        longitude: null,
        address: "Rawalpindi Road, Near Highway, Opp. Engineering University",
        short_code: "KHT",
        city_code: "KHT",
        city: "Kohat (کوہاٹ)",
      },
    ],
  },
  {
    id: 39,
    name: "Okara City (اوکاڑہ سٹی)",
    short_code: "OKR",
    terminals: [
      {
        id: 3,
        name: "Okara Cantt",
        latitude: null,
        longitude: null,
        address: null,
        short_code: null,
        city_code: "OKR",
        city: "Okara City (اوکاڑہ سٹی)",
      },
      {
        id: 239,
        name: "Okara Bus Stand",
        latitude: null,
        longitude: null,
        address: "Faisal Movers Bus Terminal General Bus Stand Okara",
        short_code: "OKR-FMB",
        city_code: "OKR",
        city: "Okara City (اوکاڑہ سٹی)",
      },
      {
        id: 52,
        name: "OKARA CITY",
        latitude: null,
        longitude: null,
        address: "Food Valley Marriage Lawn, G.T. Road",
        short_code: "OKRC",
        city_code: "OKR",
        city: "Okara City (اوکاڑہ سٹی)",
      },
    ],
  },
  {
    id: 40,
    name: "Peshawar (پشاور)",
    short_code: "PEW",
    terminals: [
      {
        id: 25,
        name: "PESHAWAR",
        latitude: null,
        longitude: null,
        address: "Opp G Bus Stand, GT Road Peshawar City",
        short_code: "PSH",
        city_code: "PEW",
        city: "Peshawar (پشاور)",
      },
      {
        id: 222,
        name: "Sadabahar Peshawar Adda",
        latitude: 31.571357314523212,
        longitude: 74.33430381534146,
        address: "Hajji Camp, Lahore Adda, GT Road",
        short_code: "PEW-HC",
        city_code: "PEW",
        city: "Peshawar (پشاور)",
      },
    ],
  },
  {
    id: 41,
    name: "Mardan (مردان)",
    short_code: "MRD",
    terminals: [
      {
        id: 74,
        name: "RASHAKAI",
        latitude: null,
        longitude: null,
        address: "",
        short_code: "RSK",
        city_code: "MRD",
        city: "Mardan (مردان)",
      },
      {
        id: 234,
        name: "Mardan College Chowk",
        latitude: null,
        longitude: null,
        address: "Sadat Travel",
        short_code: "MRD-BS",
        city_code: "MRD",
        city: "Mardan (مردان)",
      },
    ],
  },
  {
    id: 42,
    name: "Sadiqabad (صادق آباد)",
    short_code: "SAQ",
    terminals: [
      {
        id: 216,
        name: "Makka Coach Sadiqabad Point",
        latitude: 28.300002281275436,
        longitude: 70.10117952883536,
        address: "Sadiqabad General Bus Stand",
        short_code: "SAQ-GBS",
        city_code: "SAQ",
        city: "Sadiqabad (صادق آباد)",
      },
      {
        id: 7,
        name: "SADIQABAD",
        latitude: null,
        longitude: null,
        address: "KLP Road, Tehsil Sadiqabad Dist",
        short_code: "SAQ",
        city_code: "SAQ",
        city: "Sadiqabad (صادق آباد)",
      },
    ],
  },
  {
    id: 43,
    name: "Sahiwal (ساہیوال)",
    short_code: "SAW",
    terminals: [
      {
        id: 181,
        name: "Sahiwal Faisal Mover Terminal",
        latitude: null,
        longitude: null,
        address: "Faisal Movers Bus Terminal Sea Rose Hotel",
        short_code: "SAW-FM",
        city_code: "SAW",
        city: "Sahiwal (ساہیوال)",
      },
      {
        id: 2,
        name: "Sahiwal",
        latitude: null,
        longitude: null,
        address:
          "Daewoo Terminal, Near the Bank of Punjab, Arifwala Chowk, Multan Road",
        short_code: "SAHW",
        city_code: "SAW",
        city: "Sahiwal (ساہیوال)",
      },
    ],
  },
  {
    id: 44,
    name: "Sialkot (سیالکوٹ)",
    short_code: "SIAL",
    terminals: [
      {
        id: 220,
        name: "General Bus Stand Sialkot",
        latitude: null,
        longitude: null,
        address: "Bilal Travels General Bus Stand",
        short_code: "SIAL-GBS",
        city_code: "SIAL",
        city: "Sialkot (سیالکوٹ)",
      },
      {
        id: 230,
        name: "Sialkot",
        latitude: null,
        longitude: null,
        address: "Bilal Travellers Lari Adda",
        short_code: "SIAL-BTBS",
        city_code: "SIAL",
        city: "Sialkot (سیالکوٹ)",
      },
      {
        id: 31,
        name: "SIALKOT",
        latitude: null,
        longitude: null,
        address: "Garrison Park Near Jail Road, Skt Cantonment Opp. GTS",
        short_code: "SIAL",
        city_code: "SIAL",
        city: "Sialkot (سیالکوٹ)",
      },
    ],
  },
  {
    id: 45,
    name: "Sukkur (سکھر)",
    short_code: "SUK",
    terminals: [
      {
        id: 199,
        name: "Military Bypass Terminal Sukkur",
        latitude: 27.696615340691864,
        longitude: 68.84038972883533,
        address: "Main Bypass, Military Road",
        short_code: "SUK-MBP",
        city_code: "SUK",
        city: "Sukkur (سکھر)",
      },
      {
        id: 153,
        name: "Sukkur Office",
        latitude: null,
        longitude: null,
        address: "Ayub Gate Sukkur City",
        short_code: "SUK-SO",
        city_code: "SUK",
        city: "Sukkur (سکھر)",
      },
      {
        id: 10,
        name: "SUKKUR",
        latitude: null,
        longitude: null,
        address:
          "Plot no.1028 adjesent Edhi center, Baber Loi rohri By Pass, NHA. Sukkur",
        short_code: "SUK",
        city_code: "SUK",
        city: "Sukkur (سکھر)",
      },
    ],
  },
  {
    id: 46,
    name: "Lakki Marwat (لکی مروت)",
    short_code: "LMR",
    terminals: [
      {
        id: 85,
        name: "Lakki Marwat",
        latitude: null,
        longitude: null,
        address: "Gandi Chowk",
        short_code: "GDC",
        city_code: "LMR",
        city: "Lakki Marwat (لکی مروت)",
      },
    ],
  },
  {
    id: 47,
    name: "Gujranwala (گوجرانوالہ)",
    short_code: "GJW",
    terminals: [
      {
        id: 242,
        name: "General Bus Stand Gujranwala",
        latitude: null,
        longitude: null,
        address: "General Bus Stand Gujranwala",
        short_code: "GJW-GBS",
        city_code: "GJW",
        city: "Gujranwala (گوجرانوالہ)",
      },
      {
        id: 34,
        name: "GUJRANWALA",
        latitude: null,
        longitude: null,
        address:
          "Next to Rescue Office 1122, Near Qutab Autos, Ad More Petrol Pump",
        short_code: "GJW",
        city_code: "GJW",
        city: "Gujranwala (گوجرانوالہ)",
      },
    ],
  },
  {
    id: 48,
    name: "Balkasar (بلکاسر)",
    short_code: "BLK",
    terminals: [
      {
        id: 137,
        name: "Kainat Travels Balkasar Terminal",
        latitude: 32.93807558341974,
        longitude: 72.64768583068287,
        address: "Shaheen CNG, Balkasar",
        short_code: "BLK-KT",
        city_code: "BLK",
        city: "Balkasar (بلکاسر)",
      },
    ],
  },
  {
    id: 49,
    name: "Naushahro Feroze (نوشہرو فیروز)",
    short_code: "NSF",
    terminals: [
      {
        id: 149,
        name: "Naushahro Feroze Terminal",
        latitude: null,
        longitude: null,
        address: "Naushahro Feroze Bypass",
        short_code: "NSF",
        city_code: "NSF",
        city: "Naushahro Feroze (نوشہرو فیروز)",
      },
    ],
  },
  {
    id: 50,
    name: "Larkana (لاڑکانہ)",
    short_code: "LRK",
    terminals: [
      {
        id: 200,
        name: "Larkana",
        latitude: 27.563320966730146,
        longitude: 68.19290394232928,
        address: "PTS Police Station Larkana Road",
        short_code: "LRK-PTS",
        city_code: "LRK",
        city: "Larkana (لاڑکانہ)",
      },
      {
        id: 151,
        name: "Larkana Terminal",
        latitude: null,
        longitude: null,
        address: "Hameed Petroleum New Bus Stand Larkana",
        short_code: "LRK",
        city_code: "LRK",
        city: "Larkana (لاڑکانہ)",
      },
    ],
  },
  {
    id: 51,
    name: "Danda Sha Bilawal (ڈنڈا شاہ بلاول)",
    short_code: "DSB",
    terminals: [
      {
        id: 158,
        name: "Danda Sha Bilawal",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "DSB",
        city_code: "DSB",
        city: "Danda Sha Bilawal (ڈنڈا شاہ بلاول)",
      },
    ],
  },
  {
    id: 52,
    name: "Ghotki (گھوٹکی)",
    short_code: "GTK",
    terminals: [
      {
        id: 156,
        name: "Ghotki",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "GTK",
        city_code: "GTK",
        city: "Ghotki (گھوٹکی)",
      },
    ],
  },
  {
    id: 53,
    name: "Naudero (نوڈیرو)",
    short_code: "NDR",
    terminals: [
      {
        id: 157,
        name: "Naudero",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "NDR",
        city_code: "NDR",
        city: "Naudero (نوڈیرو)",
      },
    ],
  },
  {
    id: 54,
    name: "Tarhada (ترہڈا)",
    short_code: "TRD",
    terminals: [
      {
        id: 133,
        name: "Tarhada",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "TRD",
        city_code: "TRD",
        city: "Tarhada (ترہڈا)",
      },
    ],
  },
  {
    id: 55,
    name: "Talagang (تلہ گنگ)",
    short_code: "TLG",
    terminals: [
      {
        id: 30,
        name: "TALAGANG",
        latitude: null,
        longitude: null,
        address: "Near Bus Stand Ward No. 4",
        short_code: "TLG",
        city_code: "TLG",
        city: "Talagang (تلہ گنگ)",
      },
    ],
  },
  {
    id: 56,
    name: "Samundri (سمندری)",
    short_code: "SDR",
    terminals: [
      {
        id: 159,
        name: "Samundri",
        latitude: null,
        longitude: null,
        address: null,
        short_code: "SDR",
        city_code: "SDR",
        city: "Samundri (سمندری)",
      },
    ],
  },
  {
    id: 101,
    name: "Jampur",
    short_code: "JAM",
    terminals: [
      {
        id: 296,
        name: "Ghora chowk chungi Jampur",
        latitude: null,
        longitude: null,
        address: "Ghora chowk chungi, Jampur",
        short_code: "JAM-GC",
        city_code: "JAM",
        city: "Jampur",
      },
    ],
  },
];
